# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('crop_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitree_app.CropFeature')),
            ],
        ),
    ]
