# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0002_pruning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=70)),
                ('usda_zone', models.CharField(max_length=2)),
            ],
        ),
    ]
