# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0004_usdazone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdazone',
            name='name',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
