# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0007_auto_20160131_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='usda_zone',
        ),
        migrations.AddField(
            model_name='species',
            name='usda_zone',
            field=models.ManyToManyField(to='communitree_app.USDAZone'),
        ),
    ]
