# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0008_auto_20160131_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='usda_zone',
            new_name='usda_zones',
        ),
    ]
