# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0009_auto_20160131_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropfeature',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communitree_app.Species'),
        ),
    ]
