# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0010_auto_20160204_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruning',
            old_name='crop_feature',
            new_name='cropfeature',
        ),
    ]
