# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0011_auto_20160209_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cropfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitree_app.CropFeature')),
            ],
        ),
    ]
