# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0012_pruningevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruningevent',
            name='start_time',
        ),
    ]
