# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0013_remove_pruningevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruningevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
