# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.gis.geos import GEOSGeometry
from communitree_app.models import PruningEvent, CropFeature


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0014_pruningevent_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruning',
            name='cropfeature',
        ),
        migrations.AddField(
            model_name='pruning',
            name='pruningevent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communitree_app.PruningEvent'),
            preserve_default=False,
        ),
    ]
