# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitree_app', '0018_cropfeature_active_pruning_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropfeature',
            old_name='active_pruning_event',
            new_name='active_pruningevent',
        ),
    ]
